_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 86
                - 95
                - 105
            "2":
                - 1
                - 86
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 55
                - 61
            "4": 3.12.3
            "5": 0.20.1
            "8":
                - 13
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 32
buffer_size:
    value: 1000000
device:
    value: cuda
discount:
    value: 0.99
eval_freq:
    value: 10
exploration_noise:
    value: 0.1
gamma:
    value: 0.99
learning_rate:
    value: 0.001
lr_actor:
    value: 0.001
lr_critic:
    value: 0.001
max_steps:
    value: 1000000
min_steps:
    value: 100
project_name:
    value: rl_project
run_name:
    value: test
seed:
    value: 42
tau:
    value: 0.005
